### ISSUE TITLE
Refining dependency requirement in Step 0 in README

### ISSUE THREAD

**Issue by Apochens** [SVF-tools/SVF-example#67]
Without libncurses5-dev, executing the steps described in README would cause a cmake failure:

```
CMake Error at src/CMakeLists.txt:1 (add_executable):
  Target "svf-example" links to target "Terminfo::terminfo" but the target
  was not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?
```

However, libncurses5-dev is only required in the [setup guide](https://github.com/svf-tools/SVF/wiki/Setup-Guide#getting-started) of SVF.

**Comment by yuleisui** [comment]
Fixed: https://github.com/SVF-tools/SVF-example/commit/c074612d27738de776956dca29e67054336764f6
